version: "3.9"
services:
  frontend:
    build:
      context: ./client  # Use the 'client' folder as the build context
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - ./client:/app  # Keep project files in sync
      - /app/node_modules  # Ignore local node_modules
    command: ["npm", "run", "preview"]

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9800:9800"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: ["npm", "start"]
